/*  Складено автоматично: python3 tools/mklang.py
    Джерело — tools/lang/en.json. Руками не правити.  */
static const TrRow TR_EN[] = {
  { " — новіша", " — newer" },
  { "##TOUCH#\tкалібр невдало: spanX=%d spanY=%d pairOk=%d\n", "##TOUCH#\tcalib failed: spanX=%d spanY=%d pairOk=%d\n" },
  { "##TOUCH#\tкалібр: X %d..%d  Y %d..%d\n", "##TOUCH#\tcalib: X %d..%d  Y %d..%d\n" },
  { "%.1f з %.1f МБ · %u КБ/с", "%.1f of %.1f MB · %u KB/s" },
  { "%.1f°  %d мм  %d%%", "%.1f°  %d mm  %d%%" },
  { "%d кбіт/с, %s", "%d kbps, %s" },
  { "%d%% — під'єднайте зарядку", "%d%% — plug in the charger" },
  { "%d%%, %u.%02u В", "%d%%, %u.%02u V" },
  { "%d%%, %u.%02u В%s", "%d%%, %u.%02u V%s" },
  { "%s · %s · %u хв", "%s · %s · %u min" },
  { "%u КБ", "%u KB" },
  { "%u кбіт/с · %s", "%u kbps · %s" },
  { ", заряджається", ", charging" },
  { ", заряджено", ", charged" },
  { "10 с", "10 s" },
  { "15 с", "15 s" },
  { "16к", "16k" },
  { "1к", "1k" },
  { "2 стуки", "2 knocks" },
  { "2 хлопки", "2 claps" },
  { "2к", "2k" },
  { "3 стуки", "3 knocks" },
  { "3 хлопки", "3 claps" },
  { "30 с", "30 s" },
  { "4к", "4k" },
  { "60 с", "60 s" },
  { "8к", "8k" },
  { "AirPlay вимкнено", "AirPlay off" },
  { "ES8388 на цій платі немає.", "No ES8388 on this board." },
  { "GAIN і SD не під'єднувати.", "Do not connect GAIN and SD." },
  { "GitHub не назвав розмір прошивки", "GitHub did not give the firmware size" },
  { "IP-адреса на екрані", "IP address on screen" },
  { "SCK на GND, XSMT на 3V3.", "SCK to GND, XSMT to 3V3." },
  { "USB, %u.%02u В", "USB, %u.%02u V" },
  { "[готовий]", "[ready]" },
  { "[з'єднання]", "[connecting]" },
  { "[зупинено]", "[stopped]" },
  { "[наступний трек]", "[next track]" },
  { "iPhone, iPad і Mac грають на радіо будь-який звук\n(«Звук» у Пункті керування, кнопка AirPlay)", "iPhone, iPad and Mac play any sound on the radio\n(«Sound» in Control Center, the AirPlay button)" },
  { "mp3, m4a, aac, flac, wav — у будь-якій теці", "mp3, m4a, aac, flac, wav — in any folder" },
  { "Є нова версія", "Update available" },
  { "ІНДЕКС SD", "SD INDEX" },
  { "Інфо про потік", "Stream info" },
  { "Автостарт", "Autostart" },
  { "Адреса", "Address" },
  { "Анімована заставка", "Animated splash screen" },
  { "Аудіовихід", "Audio output" },
  { "БАТАРЕЯ", "BATTERY" },
  { "Баланс", "Balance" },
  { "Батарея", "Battery" },
  { "Батарея на екрані", "Battery on screen" },
  { "Батарея сідає", "Battery low" },
  { "Без зарядника пригасити через", "Dim on battery after" },
  { "Без пайки: роз'єми на звороті плати.", "No soldering: connectors on the back." },
  { "Бездротова колонка", "Wireless speaker" },
  { "Будильник", "Alarm" },
  { "Будильник і сон", "Alarm and sleep" },
  { "Версія", "Version" },
  { "Вимикаюсь…", "Turning off…" },
  { "Вимкнено", "Off" },
  { "Вимкнути", "Turn off" },
  { "Встановити", "Install" },
  { "Встановити %s", "Install %s" },
  { "Вівторок", "Tuesday" },
  { "Відомі мережі", "Known networks" },
  { "Вільна пам'ять", "Free memory" },
  { "Віртуальний бас", "Virtual bass" },
  { "ГОЛОС І ЖЕСТИ", "VOICE AND GESTURES" },
  { "ГУЧНІСТЬ", "VOLUME" },
  { "ГУЧНІСТЬ КОЖНОГО ЗВУКУ", "VOLUME OF EACH SOUND" },
  { "Гасити екран, коли тихо, хв", "Screen off when quiet, min" },
  { "Голос будить екран", "Voice wakes the screen" },
  { "Готово", "Done" },
  { "Грає", "Playing" },
  { "ДИНАМІК", "SPEAKER" },
  { "Двічі", "Double" },
  { "Де ці роз'єми на платі", "Where these connectors are" },
  { "До списку", "Back to list" },
  { "Додати вручну", "Add manually" },
  { "Дотик до екрана", "Screen touch" },
  { "ЕКРАН", "SCREEN" },
  { "Еквалайзер", "Equalizer" },
  { "Екран", "Screen" },
  { "Жест прийнято", "Gesture accepted" },
  { "Живлення", "Power" },
  { "Живлення 3–5 В.", "Power 3–5 V." },
  { "ЗАРАЗ", "NOW" },
  { "ЗАСТАВКА", "SPLASH SCREEN" },
  { "ЗВУКИ ПОДІЙ", "EVENT SOUNDS" },
  { "Забути мережу", "Forget network" },
  { "Загальна гучність", "Overall volume" },
  { "Запис", "Record" },
  { "Зараз", "Now" },
  { "Зараз звук іде сюди", "Sound goes here now" },
  { "Заставка й звуки", "Splash screen and sounds" },
  { "Захист динаміка", "Speaker protection" },
  { "Звук", "Sound" },
  { "Звуки подій", "Event sounds" },
  { "Змінити пароль", "Change password" },
  { "Зміряти", "Measure" },
  { "Зміряти ще раз", "Measure again" },
  { "Зрозуміло", "Got it" },
  { "Зупинено", "Stopped" },
  { "Зупинити", "Stop" },
  { "КАНАЛ", "CHANNEL" },
  { "Калібрування збережено", "Calibration saved" },
  { "Калібрування сенсора", "Touch calibration" },
  { "Калібрування скасовано", "Calibration cancelled" },
  { "Калібрування скинуто", "Calibration reset" },
  { "Картка", "Card" },
  { "Картка пам'яті", "Memory card" },
  { "Кодек ES8311 + підсилювач SC8002B на динамік.", "ES8311 codec + SC8002B amp to the speaker." },
  { "Колонка AirPlay", "AirPlay speaker" },
  { "Колонка DLNA", "DLNA speaker" },
  { "Кінець", "End" },
  { "ЛОГОТИПИ СТАНЦІЙ", "STATION LOGOS" },
  { "МЕРЕЖА", "NETWORK" },
  { "Меню", "Menu" },
  { "Мережа", "Network" },
  { "Мережа з'явилась", "Network found" },
  { "Мережа зникла", "Network lost" },
  { "Мережі не видно", "Network not visible" },
  { "Мережі немає. Торкніться екрана радіо й виберіть її зі списку.", "No network. Touch the radio screen and pick one from the list." },
  { "Мова", "Language" },
  { "Моно підсилювач 3 Вт на динамік 4–8 Ом.", "Mono 3 W amp for a 4–8 Ohm speaker." },
  { "Мікрофон", "Microphone" },
  { "НІЧНИЙ РЕЖИМ", "NIGHT MODE" },
  { "НЕМАЄ ЗВ'ЯЗКУ", "NO CONNECTION" },
  { "На GitHub", "On GitHub" },
  { "Назад до схеми", "Back to diagram" },
  { "Назва мережі", "Network name" },
  { "Не вдалося", "Failed" },
  { "Не вдалося з'єднатися", "Could not connect" },
  { "Невірний пароль", "Wrong password" },
  { "Неділя", "Sunday" },
  { "Немає зв'язку", "No connection" },
  { "Неточно — почніть спочатку", "Not accurate — start over" },
  { "Нічний режим", "Night mode" },
  { "Нічний режим до", "Night mode to" },
  { "Нічний режим з", "Night mode from" },
  { "ОБЛАДНАННЯ", "HARDWARE" },
  { "ОНОВЛЕННЯ", "UPDATE" },
  { "Обране", "Favorites" },
  { "Обробка", "Processing" },
  { "Оновити", "Update" },
  { "Оновлення", "Update" },
  { "Оновлення не вдалося", "Update failed" },
  { "Оновлення радіо", "Radio update" },
  { "П'ятниця", "Friday" },
  { "ПОРУЧ", "NEARBY" },
  { "ПОТУЖНЕ РАДІО", "ПОТУЖНЕ РАДІО" },
  { "ПРОШИВКА", "FIRMWARE" },
  { "Параметри", "Settings" },
  { "Пароль: %s", "Password: %s" },
  { "Перевірити зараз", "Check now" },
  { "Перезавантажити", "Restart" },
  { "Перезавантажую…", "Restarting…" },
  { "Погода", "Weather" },
  { "Показати заставку", "Show splash screen" },
  { "Показувати на головному", "Show on the main screen" },
  { "Понеділок", "Monday" },
  { "Поправка увімкнена", "Correction on" },
  { "Потрібна окрема прошивка.", "Needs separate firmware." },
  { "Потік", "Stream" },
  { "Початок", "Start" },
  { "Привітання (звук заставки)", "Greeting (splash screen sound)" },
  { "Пристрій Apple", "Apple device" },
  { "Присутність", "Presence" },
  { "Про радіо", "About" },
  { "Пробні версії", "Test versions" },
  { "Проповідь", "Sermon" },
  { "Проповіді", "Sermons" },
  { "Під кімнату", "Room" },
  { "Підключаюсь…", "Connecting…" },
  { "Підключитись", "Connect" },
  { "Пізніше", "Later" },
  { "РАДІО", "RADIO" },
  { "Радіо", "Radio" },
  { "Радіостанції", "Radio stations" },
  { "Розробник", "Developer" },
  { "СВІТЛОДІОД НА ПЛАТІ", "LED ON THE BOARD" },
  { "СЕНСОР", "TOUCH" },
  { "СИСТЕМА", "SYSTEM" },
  { "СТЕРЕО", "STEREO" },
  { "Середа", "Wednesday" },
  { "Сигнал", "Signal" },
  { "Скинути калібрування", "Reset calibration" },
  { "Слухати", "Listen" },
  { "Слухати й під час звуку", "Listen while sound plays" },
  { "Сон", "Sleep" },
  { "Стан батареї", "Battery status" },
  { "Станції", "Stations" },
  { "Стерео ЦАП, лінійний вихід 3.5 мм.", "Stereo DAC, 3.5 mm line out." },
  { "Стерео ЦАП: навушники й лінійний вихід.", "Stereo DAC: headphones and line out." },
  { "Субота", "Saturday" },
  { "ТАЙМЕР СНУ", "SLEEP TIMER" },
  { "ТАЙМЕР СНУ, ХВ", "SLEEP TIMER, MIN" },
  { "Таймер сну", "Sleep timer" },
  { "Таймер сну слухає", "Sleep timer listens" },
  { "Тонкомпенсація, коли тихо", "Loudness when quiet" },
  { "Торкайтесь точно центру позначки", "Tap exactly in the center of the mark" },
  { "Торкніться позначки  %u/4", "Tap the mark  %u/4" },
  { "Торкніться ще раз — забуду", "Tap again — I will forget it" },
  { "Тричі", "Triple" },
  { "У кімнаті тихо, хв", "Room quiet for, min" },
  { "У радіо", "In the radio" },
  { "Увімкнено", "On" },
  { "Увімкнути цей вихід", "Turn on this output" },
  { "Хлопки й стук", "Claps and knocks" },
  { "Часовий пояс", "Time zone" },
  { "Четвер", "Thursday" },
  { "Чутливість", "Sensitivity" },
  { "Шукати логотипи знову", "Look for logos again" },
  { "Шукати ще раз", "Scan again" },
  { "ЩО ВМІЄ", "WHAT IT CAN DO" },
  { "ЩО ПОКАЗУВАТИ", "WHAT TO SHOW" },
  { "ЩО РОБИТИ", "WHAT TO DO" },
  { "Ще раз", "Try again" },
  { "Яскравість", "Brightness" },
  { "Яскравість уночі", "Brightness at night" },
  { "адреса сайту", "site address" },
  { "бас", "bass" },
  { "батарея %d%% — під'єднайте зарядку", "battery %d%% — plug in the charger" },
  { "без картки", "no card" },
  { "березня", "March" },
  { "будні", "weekdays" },
  { "вбудований кодек і підсилювач", "built-in codec and amp" },
  { "вересня", "September" },
  { "виберіть мережу зі списку — радіо запам'ятає її", "pick a network from the list — the radio will remember it" },
  { "виберіть мережу, щоб радіо почало грати", "pick a network so the radio can play" },
  { "вийшла нова версія", "a new version is out" },
  { "вимк", "off" },
  { "вимкнено · заграє %s", "off · will play %s" },
  { "вимірюю…", "measuring…" },
  { "висока", "high" },
  { "вона зникла з ефіру", "it is gone off the air" },
  { "віднімаю власний звук радіо", "subtracting the radio's own sound" },
  { "години від Гринвіча (Київ: +2 взимку, +3 влітку)", "hours from Greenwich (Kyiv: +2 in winter, +3 in summer)" },
  { "голос", "voice" },
  { "готово", "done" },
  { "готово, перезавантажуюсь", "done, restarting" },
  { "грудня", "December" },
  { "гучність 0 — звуку не буде", "volume 0 — there will be no sound" },
  { "гучність цього звуку 0", "volume of this sound is 0" },
  { "гучніше", "louder" },
  { "динамік", "speaker" },
  { "для станцій, де минулого разу не знайшлося", "for stations where none was found last time" },
  { "додайте станції на сторінці радіо в браузері", "add stations on the radio page in a browser" },
  { "додано в обране", "added to favorites" },
  { "додати", "add" },
  { "дотиком або будильником о %02u:%02u", "by touch or by alarm at %02u:%02u" },
  { "екран", "screen" },
  { "жовтня", "October" },
  { "жодної мережі не збережено", "no networks saved" },
  { "з картки", "from card" },
  { "з мережі", "from network" },
  { "з неї радіо починає", "the radio starts with it" },
  { "за мить заграє", "it will play in a moment" },
  { "за мить радіо увімкнеться знову", "the radio will turn on again in a moment" },
  { "завантаження обірвалось — спробуйте ще раз", "download was cut off — try again" },
  { "завантажую з сайту…", "loading from the site…" },
  { "завантажую з сайту… %u", "loading from the site… %u" },
  { "завантажую й записую прошивку", "downloading and writing firmware" },
  { "завантажую сторінку радіо", "downloading the radio page" },
  { "задача не створилась", "task was not created" },
  { "запасна", "backup" },
  { "запис зупинено", "recording stopped" },
  { "запис лише з радіо", "recording from radio only" },
  { "записую нову прошивку…", "writing the new firmware…" },
  { "зараз звук іде сюди", "sound goes here now" },
  { "заставка", "splash screen" },
  { "заставка, звуки", "splash screen, sounds" },
  { "звертаюсь до GitHub…", "asking GitHub…" },
  { "звук не зупиняється", "sound will not stop" },
  { "звук стихне на 10 секунд", "sound goes quiet for 10 seconds" },
  { "звук іде на зовнішній ЦАП", "sound goes to the external DAC" },
  { "звук іде на зовнішній ЦАП, вбудований динамік вимкнено", "sound goes to the external DAC, built-in speaker is off" },
  { "звук іде на цей вихід", "sound goes to this output" },
  { "звуки", "sounds" },
  { "знайдено файлів: %ld", "files found: %ld" },
  { "зупиняю звук", "stopping the sound" },
  { "картку вимкнено (розробник)", "card is off (developer)" },
  { "картку вимкнено в «Розробнику»", "card is off in «Developer»" },
  { "квітня", "April" },
  { "кнопка з трикутником — прослухати звук;\nсвій звук (MP3 чи WAV) і які події озвучувати —\nна сторінці радіо: Розробник › Звуки подій", "the triangle button — hear the sound;\nyour own sound (MP3 or WAV) and which events to voice —\non the radio page: Developer › Event sounds" },
  { "колонку вимкнено", "speaker off" },
  { "крутіть години й хвилини пальцем\nабо торкніться значення вище чи нижче", "spin the hours and minutes with a finger\nor tap a value above or below" },
  { "липня", "July" },
  { "листопада", "November" },
  { "лише випуски для всіх; увімкніть, щоб ставити пробні", "only releases for everyone; turn on to install test ones" },
  { "лише радіо", "radio only" },
  { "лютого", "February" },
  { "м'яка", "gentle" },
  { "м'який", "gentle" },
  { "макс", "max" },
  { "мереж не знайдено", "no networks found" },
  { "мережа не відповідає", "the network is not answering" },
  { "мережу забуто", "network forgotten" },
  { "моно підсилювач 3 Вт на динамік", "mono 3 W amp for a speaker" },
  { "музика", "music" },
  { "мікрофон вимкнено", "microphone off" },
  { "мікрофон вимкнено — жести не слухаються", "microphone off — gestures are not heard" },
  { "мікрофон не запущено", "microphone not started" },
  { "мікрофон не слухає", "microphone is not listening" },
  { "мікрофон не чує тонів", "microphone does not hear the tones" },
  { "мікрофон спотворює звук", "microphone distorts the sound" },
  { "мікрофон чує, чи є в кімнаті люди", "the microphone hears whether people are in the room" },
  { "на GitHub ще немає випуску", "no release on GitHub yet" },
  { "на картці мало місця", "little space on the card" },
  { "на картці немає музики", "no music on the card" },
  { "нагадую щохвилини, поки не під'єднаєте", "I will remind every minute until you plug it in" },
  { "наступна", "next" },
  { "не вдалося записати прошивку", "could not write the firmware" },
  { "не вдалося звернутися до GitHub", "could not reach GitHub" },
  { "не вийшло", "did not work" },
  { "не вийшло: %s", "did not work: %s" },
  { "не вимикайте радіо", "do not turn off the radio" },
  { "не знайдено", "not found" },
  { "не показується", "hidden" },
  { "не підключено", "not connected" },
  { "незрозуміла відповідь GitHub", "unclear answer from GitHub" },
  { "нема картки", "no card" },
  { "нема мережі", "no network" },
  { "нема пам'яті", "out of memory" },
  { "немає", "none" },
  { "немає мережі", "no network" },
  { "немає місця для нової прошивки", "no room for the new firmware" },
  { "немає придатного заміру", "no usable measurement" },
  { "низька", "low" },
  { "ні", "no" },
  { "ніч", "night" },
  { "нічого", "nothing" },
  { "нічого не грає", "nothing is playing" },
  { "обране 1", "favorite 1" },
  { "окремий декодер, інша прошивка", "separate decoder, other firmware" },
  { "оновитись пізніше: Меню » Оновлення", "update later: Menu » Update" },
  { "оновлення з GitHub", "update from GitHub" },
  { "остання", "latest" },
  { "остання станція", "the last station" },
  { "пауза / грати", "pause / play" },
  { "перебере решту по черзі", "it tries the rest in turn" },
  { "перевірте й введіть ще раз", "check it and type again" },
  { "перевіряю GitHub", "checking GitHub" },
  { "перевіряю мікрофон", "checking the microphone" },
  { "перевіряю прошивку", "checking the firmware" },
  { "перевіряю результат", "checking the result" },
  { "перевіряю…", "checking…" },
  { "перервано", "cancelled" },
  { "перша — з неї радіо починає; немає її в ефірі —", "the first one is where the radio starts; if it is off the air —" },
  { "пишу ефір на картку", "recording to the card" },
  { "плата (роз'єм)", "board (connector)" },
  { "плесніть чи постукайте двічі", "clap or knock twice" },
  { "помилка запису на картку", "error writing to the card" },
  { "попередня", "previous" },
  { "поправка не потрібна (%.1f дБ)", "no correction needed (%.1f dB)" },
  { "почуто: %s — %s", "heard: %s — %s" },
  { "прибрано з обраного", "removed from favorites" },
  { "пробіл", "space" },
  { "проповідей не знайдено", "no sermons found" },
  { "пропонувати й попередні випуски — ще не перевірені для всіх", "offer pre-releases too — not yet tested for everyone" },
  { "прошивка не пройшла перевірку", "firmware failed the check" },
  { "прошивка: код %d", "firmware: code %d" },
  { "підключено · %s", "connected · %s" },
  { "радіо видно в AirPlay", "radio shows in AirPlay" },
  { "радіо видно в мережі як колонку", "radio shows on the network as a speaker" },
  { "радіо грає тони й слухає себе мікрофоном;\nу кімнаті має бути тихо", "the radio plays tones and listens to itself;\nthe room must be quiet" },
  { "радіо замовкне через %u:%02u", "radio goes quiet in %u:%02u" },
  { "радіо зараз не в мережі", "the radio is not on a network" },
  { "радіо зараз тут", "the radio is here now" },
  { "радіо працює на старій версії", "the radio runs the old version" },
  { "радіо саме перевіряє GitHub двічі на добу", "the radio checks GitHub twice a day itself" },
  { "радіо саме підключається до мережі…", "the radio is connecting to a network…" },
  { "радіо спробує просто зараз і скаже, чи вийшло", "the radio will try right now and tell you if it worked" },
  { "роз'єм I2C", "I2C connector" },
  { "роз'єм UART", "UART connector" },
  { "роз'єм розширення (Expand)", "expansion connector (Expand)" },
  { "рівно", "flat" },
  { "рівніше: %.1f -> %.1f дБ", "flatter: %.1f -> %.1f dB" },
  { "сайт відповів помилкою", "site answered with an error" },
  { "сайт недоступний", "site is unreachable" },
  { "свій", "custom" },
  { "середня", "medium" },
  { "серпня", "August" },
  { "сильна", "strong" },
  { "сильний", "strong" },
  { "слухаю", "listening" },
  { "слухаю тони", "listening to tones" },
  { "спершу зміряйте", "measure first" },
  { "спершу зупиніть звук", "stop the sound first" },
  { "спершу увімкніть радіостанцію", "turn on a station first" },
  { "список порожній", "the list is empty" },
  { "список станцій порожній", "the station list is empty" },
  { "стан", "status" },
  { "станції, мережі, обране й налаштування лишаються;\nпід час оновлення радіо не вимикати", "stations, networks, favorites and settings stay;\ndo not turn off the radio while updating" },
  { "стерео ЦАП, лінійний вихід", "stereo DAC, line out" },
  { "стерео ЦАП, навушники й лінія", "stereo DAC, headphones and line" },
  { "стук", "knocks" },
  { "січня", "January" },
  { "таймер вимкнено", "timer off" },
  { "таймер сну вимкнено", "sleep timer off" },
  { "таймер сну: %u хв", "sleep timer: %u min" },
  { "телефон чи комп'ютер надсилає радіо доріжку\n(BubbleUPnP, VLC, «Передати на пристрій»)", "a phone or computer sends the radio a track\n(BubbleUPnP, VLC, «Cast to device»)" },
  { "тепер вона перша", "now it is first" },
  { "тепло", "warm" },
  { "типово", "default" },
  { "тихіше", "quieter" },
  { "торкніться порожньої — додати станцію, що грає; утримайте — прибрати", "tap an empty one — add the station playing; hold — remove" },
  { "торкніться ще раз — забуду", "tap again — I will forget it" },
  { "торкніться — вибрати іншу мережу", "tap — pick another network" },
  { "торкніться, щоб завантажити", "tap to load" },
  { "травня", "May" },
  { "тримайте, поки коло не замкнеться", "hold until the circle closes" },
  { "у радіо остання версія", "radio has the latest version" },
  { "увімк", "on" },
  { "увімкнеться дотиком до екрана", "turns on with a screen touch" },
  { "уже зайнятий", "already busy" },
  { "уже міряю", "already measuring" },
  { "уже налаштовую", "already tuning" },
  { "уточнюю (%u)", "refining (%u)" },
  { "утримайте кнопку ~1 секунду", "hold the button ~1 second" },
  { "файл не створився", "file was not created" },
  { "файл сторінки обірвався", "page file was cut off" },
  { "файл сторінки: код %d", "page file: code %d" },
  { "хлопки", "claps" },
  { "хлопки, стук", "claps, knocks" },
  { "це займає кілька секунд", "this takes a few seconds" },
  { "цієї станції вже нема в списку", "this station is no longer in the list" },
  { "час ще не відомий · заграє %s", "time not known yet · will play %s" },
  { "червня", "June" },
  { "через %d год %02d хв · заграє %s", "in %d h %02d min · will play %s" },
  { "читаю список треків…", "reading the track list…" },
  { "чую голос", "I hear a voice" },
  { "шукатиму знову: %u", "will look again: %u" },
  { "шукаю мережі…", "looking for networks…" },
  { "шукаю…", "scanning…" },
  { "ще не міряли", "not measured yet" },
  { "ще не перевіряли", "not checked yet" },
  { "щодня", "every day" },
  { "якщо дотик б'є мимо: торкніться чотирьох позначок по кутах", "if touch misses: tap the four marks in the corners" },
  { "яскраво", "bright" },
  { "є %s", "new %s" },
  { "іде…", "updating…" },
};
